### PR TITLE
Fix crash in mipSamples setter

### PR DESCRIPTION
**Pull request by pawsong**
There might be an unintended change in 40502cc8b80fc8521b07a1d27739659215da763e :)

### CODE REVIEW

**Comment by mikolalysenko** [comment]
Thanks!

**Comment by pawsong** [comment]
@mikolalysenko You're welcome! Anyway, I am a big fan of you. I can't imagine writing code without your outstanding works like ndarray, cwise, meshers and so on. Just wanted to express my gratitude. Have a nice day :)

**Comment by mikolalysenko** [comment]
Glad it's all been helpful for you.  Also if you are still doing WebGL stuff you might want to check out [regl](https://github.com/mikolalysenko/regl) which is a new thing I've been building.

**Comment by pawsong** [comment]
[regl](/mikolalysenko/regl) might be the most promising library in WebGL eceosystem :) I am considering using it for the next project. Thanks again!

**Pull request merged**
